#!/usr/bin/env python3
"""Create consistent SpreadBoard snapshots and send them to encrypted restic storage."""

from __future__ import annotations

from contextlib import closing
from datetime import datetime, timezone
import os
from pathlib import Path
import re
import shutil
import sqlite3
import subprocess
import tempfile
import time


RUNTIME_DIR = Path(os.environ.get("SPREADBOARD_BACKUP_SOURCE", "/opt/spreadboard/runtime"))
RESTIC = os.environ.get("SPREADBOARD_RESTIC_BIN", "restic")
RETENTION_DAILY = os.environ.get("SPREADBOARD_BACKUP_KEEP_DAILY", "7")
RETENTION_WEEKLY = os.environ.get("SPREADBOARD_BACKUP_KEEP_WEEKLY", "4")
RETENTION_MONTHLY = os.environ.get("SPREADBOARD_BACKUP_KEEP_MONTHLY", "3")
#: `forget --prune` needs an EXCLUSIVE lock, so it is the one step a stale lock
#: from a killed run can block. Wait this long for a genuinely concurrent run
#: rather than failing instantly, as the 12 September run did at "up to 0s".
LOCK_RETRY = os.environ.get("SPREADBOARD_BACKUP_LOCK_RETRY", "15m")
DATABASE_SUFFIXES = {".sqlite", ".sqlite3", ".db"}
# Raw discovery archives reach several gigabytes a day and are regenerated by
# the collector, so bulk files stay out of the repository. Databases are exempt:
# see _excluded.
MAX_COPIED_FILE_BYTES = int(
    os.environ.get("SPREADBOARD_BACKUP_MAX_FILE_BYTES", str(250 * 1024 * 1024))
)


def _lock_retry_seconds(value: str) -> float:
    """Parse the bounded s/m/h durations accepted by our operator setting."""
    parts = re.findall(r"(\d+(?:\.\d+)?)(ms|s|m|h)", value)
    if not parts or "".join(number + unit for number, unit in parts) != value:
        raise ValueError("invalid_backup_lock_retry_duration")
    seconds = sum(float(number) * {"ms": .001, "s": 1, "m": 60, "h": 3600}[unit]
                  for number, unit in parts)
    if not 0 <= seconds <= 3600:
        raise ValueError("backup_lock_retry_exceeds_one_hour")
    return seconds


def _run_restic(command: list[str], **kwargs):
    """Pace the rclone backend without changing other repository backends."""
    # Retention repacking holds an EXCLUSIVE lock that can last hours, and the
    # repository probe, the backup and the check all need a lock of their own.
    # Without this they fail at "waiting up to 0s for the lock" and lose the
    # whole run. Global flag in restic 0.16+, inserted after the subcommand so
    # backend options stay last.
    if len(command) > 1 and "--retry-lock" not in command:
        command = [*command[:2], "--retry-lock", LOCK_RETRY, *command[2:]]
    if os.environ.get("RESTIC_REPOSITORY", "").strip().startswith("rclone:"):
        command = [*command, "-o", "rclone.timeout=5m", "-o", "rclone.connections=2"]
        environment = dict(os.environ)
        environment.setdefault("RCLONE_TPSLIMIT", "4")
        environment.setdefault("RCLONE_TPSLIMIT_BURST", "1")
        kwargs["env"] = environment
        # Allow the backend's five-minute opening window to finish before
        # the bounded repository probe kills it at the former two minutes.
        if "timeout" in kwargs:
            kwargs["timeout"] = max(360, kwargs["timeout"])
    if "timeout" in kwargs and "--retry-lock" in command:
        # A 120s (or rclone 360s) subprocess timeout previously killed restic
        # inside its advertised 15m lock wait. Budget both phases, not max().
        retry = command[command.index("--retry-lock") + 1]
        kwargs["timeout"] += _lock_retry_seconds(retry)
    return subprocess.run(command, check=kwargs.pop("check", False), **kwargs)


def stage_snapshot(source: Path, target: Path) -> list[Path]:
    """Stage consistent databases plus small operational state files."""
    copied: list[Path] = []
    for path in sorted(source.rglob("*")):
        if not path.is_file() or _excluded(path, source):
            continue
        relative = path.relative_to(source)
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        if path.suffix.casefold() in DATABASE_SUFFIXES:
            try:
                _backup_sqlite(path, destination)
            except sqlite3.DatabaseError as exc:
                raise RuntimeError(f"backup_sqlite_failed:{relative.as_posix()}") from exc
        else:
            shutil.copy2(path, destination)
        copied.append(relative)
    manifest = target / "BACKUP-MANIFEST.txt"
    manifest.write_text(
        "created_at=" + datetime.now(tz=timezone.utc).isoformat() + "\n"
        + "files=" + str(len(copied)) + "\n",
        encoding="utf-8",
    )
    return copied


def run_backup() -> None:
    _require_restic_configuration()
    if not RUNTIME_DIR.is_dir():
        raise RuntimeError("backup_source_missing")
    _ensure_repository()
    with tempfile.TemporaryDirectory(prefix="spreadboard-backup-") as temporary:
        stage = Path(temporary) / "spreadboard-runtime"
        stage.mkdir()
        copied = stage_snapshot(RUNTIME_DIR, stage)
        if not copied:
            raise RuntimeError("backup_source_empty")
        _run_restic(
            [RESTIC, "backup", "--tag", "spreadboard", "--host", "spreadboard-prod",
             "--group-by", "host,tags", str(stage)],
            check=True,
        )
        # `_ensure_repository` unlocks only when its probe is blocked, and that
        # probe (`restic snapshots`) takes a non-exclusive lock: a stale lock
        # that blocks just exclusive operations sails past it and then fails
        # retention, throwing away a snapshot already saved. Sweep stale locks
        # here, where the exclusive step actually runs. restic's default unlock
        # is age- and owner-checked; --remove-all must never be used.
        _run_restic([RESTIC, "unlock"], check=False, timeout=120)
        _run_restic(
            [
                RESTIC,
                "forget",
                "--tag",
                "spreadboard",
                "--host",
                "spreadboard-prod",
                # Each consistent staging copy has a new temporary path.
                # Grouping by paths kept every snapshot in its own group and
                # made daily/weekly/monthly retention ineffective. Scope this
                # policy to this host/tag, including its older staged paths.
                "--group-by",
                "host,tags",
                "--keep-daily",
                RETENTION_DAILY,
                "--keep-weekly",
                RETENTION_WEEKLY,
                "--keep-monthly",
                RETENTION_MONTHLY,
                "--prune",
            ],
            check=True,
        )
        _run_restic([RESTIC, "check", "--read-data-subset=1/20"], check=True)


def _ensure_repository() -> None:
    # A transient repository probe must not discard the entire six-hour run.
    # Keep retries bounded and never echo provider stderr or configuration.
    reason = "backend_unavailable"
    for attempt, delay in enumerate((0, 10, 30), start=1):
        if delay:
            time.sleep(delay)
        try:
            probe = _run_restic(
                [RESTIC, "snapshots", "--json"], capture_output=True,
                text=True, check=False, timeout=120,
            )
        except subprocess.TimeoutExpired:
            reason = "backend_timeout"
        else:
            if probe.returncode == 0:
                return
            combined = f"{probe.stdout}\n{probe.stderr}".casefold()
            if "unable to open config file" in combined or "is there a repository at" in combined:
                _run_restic([RESTIC, "init"], check=True)
                return
            reason = "backend_unavailable"
            if "repository is already locked" in combined:
                # Never remove live locks. restic's default unlock checks age
                # and owner liveness; --remove-all must never be used here.
                unlock = _run_restic(
                    [RESTIC, "unlock"], capture_output=True, text=True,
                    check=False, timeout=120,
                )
                reason = "backend_locked" if unlock.returncode == 0 else "backend_unlock_failed"
            for marker, category in (
                ("rate_limit_exceeded", "backend_rate_limited"),
                ("ratelimitexceeded", "backend_rate_limited"),
                ("read-only file system", "backend_config_write_denied"),
                ("invalid_grant", "backend_auth_failed"),
            ):
                if marker in combined:
                    reason = category
                    break
        print(f"backup repository probe attempt={attempt} status={reason}", flush=True)
    raise RuntimeError(f"backup_repository_unavailable:{reason}")


def _backup_sqlite(source: Path, destination: Path) -> None:
    try:
        with closing(sqlite3.connect(f"file:{source}?mode=ro", uri=True)) as source_db:
            with closing(sqlite3.connect(destination)) as destination_db:
                source_db.backup(destination_db)
    except sqlite3.DatabaseError:
        # A file with a database suffix may be an incomplete cache. Never turn
        # a failed consistency check into a successful-looking backup.
        destination.unlink(missing_ok=True)
        raise


def _excluded(path: Path, root: Path) -> bool:
    relative = path.relative_to(root)
    name = path.name.casefold()
    if any(part in {"__pycache__", "historical_spread_cache", "restic-cache"} for part in relative.parts):
        return True
    if name.endswith(("-wal", "-shm", ".tmp", ".log")):
        return True
    # Databases are the payload this backup exists for and they outgrow any
    # sensible bulk-file cap: market history alone passed two gigabytes. Capping
    # them by size produced successful-looking snapshots that silently held no
    # route history, so size only ever excludes non-database files.
    if path.suffix.casefold() in DATABASE_SUFFIXES:
        return False
    return path.stat().st_size > MAX_COPIED_FILE_BYTES


def _require_restic_configuration() -> None:
    """Demand what this backend actually uses, and nothing more.

    The repository and its password are universal: without the password the
    snapshot is not ciphertext. AWS keys belong to S3-compatible backends only.
    Requiring them unconditionally made every other backend unreachable --
    including rclone, which carries its own credentials.
    """
    required = ["RESTIC_REPOSITORY", "RESTIC_PASSWORD_FILE"]
    if os.environ.get("RESTIC_REPOSITORY", "").strip().startswith("s3:"):
        required += ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY"]
    missing = [name for name in required if not os.environ.get(name)]
    if missing:
        raise RuntimeError("backup_configuration_missing:" + ",".join(missing))


if __name__ == "__main__":
    run_backup()
